vich_uploader:
    db_driver: orm

    mappings:
        justificatif:
            uri_prefix: /images/justificatifs
            upload_destination: '%kernel.project_dir%/public/images/justificatifs'
